### PR TITLE
New file is opened in existing window instead of new one.

### PR DESCRIPTION
**Pull request by Trudko**
In issue Stay in window. #11 few people wanted new file to open in same window instead of new one, which IMHO make sense. @rev087  Can you please merge?

### CODE REVIEW

**Comment by Trudko** [comment]
@silentvick i really can't reproduce the original bug :) Do you still have the problem?

**Comment by silentvick** [comment]
@Trudko , sorry for the late response. I've managed to solve that issue. It appeared to be a cache problem. Atom compiles cofee-scripts in `~/.atom/compile-cache/cofee` directory. And for some reason it was using an old cached code. So I just had to clear the cache and that solved my problem. Anyway, thanks for the PR and for your help! :)

**Comment by Trudko** [comment]
@silentvick so did my pull request work for you ? :) And you are welcome ofc!

**Comment by silentvick** [comment]
@Trudko , yep, it works fine now :)

**Comment by stdavis** [comment]
:+1: on a merge for the PR. Would love to have the new file open in the same window.

Thanks for the awesome package.

**Comment by Trudko** [comment]
@silentvick @stdavis  and others, I have decied to fork this package and I have published it :) https://atom.io/packages/advanced-new-file. I fix this and one other bug I found and also added posibility of creating multiple files at once(by comma separation). Please check  :)

**Comment by Trudko** [comment]
Closing the pull request it was implemented in package mentioned above.

**Pull request closed without merging**
